In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

Load data, should be placed in folder called 'Data'

In [45]:
df_0 = pd.read_csv("Training_Set_Values.csv")
df_1 = pd.read_csv("Training_Set_labels.csv")
merged_df = df_0.merge(df_1, on='id')
merged_df

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,status_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,...,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,...,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,...,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,functional
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,...,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,...,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59395,60739,10.0,2013-05-03,Germany Republi,1210,CES,37.169807,-3.253847,Area Three Namba 27,0,...,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
59396,27263,4700.0,2011-05-07,Cefa-njombe,1212,Cefa,35.249991,-9.070629,Kwa Yahona Kuvala,0,...,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe,functional
59397,37057,0.0,2011-04-11,NaN,0,NaN,34.017087,-8.750434,Mashine,0,...,fluoride,fluoride,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump,functional
59398,31282,0.0,2011-03-08,Malec,0,Musa,35.861315,-6.378573,Mshoro,0,...,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump,functional
59399,26348,0.0,2011-03-23,World Bank,191,World,38.104048,-6.747464,Kwa Mzee Lugawa,0,...,salty,salty,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,functional

Which column contains NaN? Corrosponding to which id?

In [4]:
nan_locs = np.where(df.isna())

for row, col in zip(*nan_locs):
    row_id = df.iloc[row]["id"]
    col_name = df.columns[col]
    print(f"NaN found in row with id {row_id}, column '{col_name}'")

NaN found in row with id 8776, column 'public_meeting'
NaN found in row with id 8776, column 'scheme_name'
NaN found in row with id 67743, column 'scheme_name'
NaN found in row with id 19728, column 'scheme_management'
NaN found in row with id 19728, column 'scheme_name'
NaN found in row with id 19816, column 'scheme_name'
NaN found in row with id 54551, column 'scheme_management'
NaN found in row with id 54551, column 'scheme_name'
NaN found in row with id 53934, column 'scheme_name'
NaN found in row with id 46144, column 'scheme_management'
NaN found in row with id 46144, column 'scheme_name'
NaN found in row with id 49056, column 'scheme_name'
NaN found in row with id 50409, column 'scheme_name'
NaN found in row with id 36957, column 'scheme_name'
NaN found in row with id 53752, column 'scheme_name'
NaN found in row with id 61848, column 'scheme_name'
NaN found in row with id 34169, column 'public_meeting'
NaN found in row with id 34169, column 'scheme_management'
NaN found in row with id 34169, column 'scheme_name'
NaN found in row with id 20145, column 'scheme_management'
NaN found in row with id 20145, column 'scheme_name'
NaN found in row with id 46804, column 'scheme_name'
NaN found in row with id 41583, column 'funder'
NaN found in row with id 41583, column 'installer'
NaN found in row with id 41583, column 'scheme_name'
NaN found in row with id 57355, column 'scheme_management'
NaN found in row with id 57355, column 'scheme_name'
NaN found in row with id 25, column 'scheme_name'
NaN found in row with id 19282, column 'funder'
NaN found in row with id 19282, column 'installer'
NaN found in row with id 19282, column 'permit'
NaN found in row with id 45111, column 'scheme_name'
NaN found in row with id 13620, column 'funder'
NaN found in row with id 13620, column 'installer'
NaN found in row with id 13620, column 'permit'
NaN found in row with id 9417, column 'scheme_management'
NaN found in row with id 9417, column 'scheme_name'
NaN found in row with id 24593, column 'public_meeting'
NaN found in row with id 24593, column 'scheme_name'
NaN found in row with id 31714, column 'scheme_name'
NaN found in row with id 40393, column 'scheme_name'
NaN found in row with id 51072, column 'funder'
NaN found in row with id 51072, column 'installer'
NaN found in row with id 51072, column 'permit'
NaN found in row with id 34255, column 'scheme_name'
NaN found in row with id 54801, column 'scheme_name'
NaN found in row with id 21990, column 'scheme_management'
NaN found in row with id 21990, column 'scheme_name'
NaN found in row with id 17386, column 'funder'
NaN found in row with id 17386, column 'installer'
NaN found in row with id 17386, column 'scheme_name'
NaN found in row with id 41609, column 'funder'
NaN found in row with id 41609, column 'installer'
NaN found in row with id 41609, column 'scheme_name'
NaN found in row with id 35715, column 'public_meeting'
NaN found in row with id 35715, column 'scheme_name'
NaN found in row with id 53970, column 'scheme_name'
NaN found in row with id 62971, column 'funder'
NaN found in row with id 62971, column 'installer'
NaN found in row with id 62971, column 'scheme_name'
NaN found in row with id 52561, column 'scheme_name'
NaN found in row with id 34383, column 'scheme_name'
NaN found in row with id 30423, column 'public_meeting'
NaN found in row with id 30423, column 'scheme_name'
NaN found in row with id 3688, column 'scheme_name'
NaN found in row with id 30537, column 'scheme_management'
NaN found in row with id 62591, column 'scheme_name'
NaN found in row with id 48593, column 'scheme_name'
NaN found in row with id 68554, column 'scheme_name'
NaN found in row with id 29083, column 'scheme_name'
NaN found in row with id 17970, column 'scheme_name'
NaN found in row with id 25693, column 'scheme_name'
NaN found in row with id 59902, column 'scheme_name'
NaN found in row with id 60371, column 'scheme_name'
NaN found in row with id 7116, column 'funder'
NaN found in row with id 7116, column 'installer'
NaN found in row with id 7116, column 'permit'
NaN found in row with id 10784, column 'scheme_name'
NaN found in row with id 49503, column 'scheme_name'
NaN found in row with id 21068, column 'scheme_name'
NaN found in row with id 62341, column 'scheme_name'
NaN found in row with id 10837, column 'scheme_name'
NaN found in row with id 10837, column 'permit'
NaN found in row with id 64447, column 'scheme_name'
NaN found in row with id 2915, column 'scheme_name'
NaN found in row with id 2915, column 'permit'
NaN found in row with id 14016, column 'funder'
NaN found in row with id 14016, column 'installer'
NaN found in row with id 14016, column 'permit'
NaN found in row with id 69525, column 'scheme_name'
NaN found in row with id 73061, column 'funder'
NaN found in row with id 73061, column 'installer'
NaN found in row with id 73061, column 'permit'
NaN found in row with id 33235, column 'scheme_management'
NaN found in row with id 33235, column 'scheme_name'
NaN found in row with id 41839, column 'public_meeting'
NaN found in row with id 41839, column 'scheme_name'
NaN found in row with id 62002, column 'scheme_name'
NaN found in row with id 25915, column 'funder'
NaN found in row with id 25915, column 'installer'
NaN found in row with id 25915, column 'scheme_name'
NaN found in row with id 20673, column 'scheme_management'
NaN found in row with id 20673, column 'scheme_name'
NaN found in row with id 69107, column 'scheme_name'
NaN found in row with id 44002, column 'scheme_name'
NaN found in row with id 37471, column 'scheme_name'
NaN found in row with id 64130, column 'scheme_name'
NaN found in row with id 28669, column 'public_meeting'
NaN found in row with id 28669, column 'scheme_name'
NaN found in row with id 73769, column 'scheme_name'
NaN found in row with id 66521, column 'scheme_name'
NaN found in row with id 53167, column 'scheme_management'
NaN found in row with id 53167, column 'scheme_name'
NaN found in row with id 24232, column 'funder'
NaN found in row with id 24232, column 'installer'
NaN found in row with id 24232, column 'scheme_name'
NaN found in row with id 65788, column 'scheme_management'
NaN found in row with id 65788, column 'scheme_name'
NaN found in row with id 72981, column 'funder'
NaN found in row with id 72981, column 'installer'
NaN found in row with id 72981, column 'scheme_name'
NaN found in row with id 60983, column 'scheme_name'
NaN found in row with id 37768, column 'public_meeting'
NaN found in row with id 37768, column 'scheme_name'
NaN found in row with id 64880, column 'scheme_name'
NaN found in row with id 32871, column 'scheme_name'
NaN found in row with id 45564, column 'scheme_name'
NaN found in row with id 23519, column 'public_meeting'
NaN found in row with id 23519, column 'scheme_name'
NaN found in row with id 50173, column 'scheme_name'
NaN found in row with id 66843, column 'installer'
NaN found in row with id 13815, column 'scheme_name'
NaN found in row with id 36591, column 'scheme_name'
NaN found in row with id 63632, column 'scheme_name'
NaN found in row with id 11787, column 'scheme_name'
NaN found in row with id 48528, column 'scheme_name'
NaN found in row with id 50970, column 'scheme_name'
NaN found in row with id 12120, column 'scheme_management'
NaN found in row with id 12120, column 'scheme_name'
NaN found in row with id 67980, column 'scheme_name'
NaN found in row with id 14884, column 'scheme_name'
NaN found in row with id 33037, column 'scheme_name'
NaN found in row with id 68908, column 'funder'
NaN found in row with id 68908, column 'installer'
NaN found in row with id 68908, column 'scheme_name'
NaN found in row with id 60866, column 'scheme_name'
NaN found in row with id 2136, column 'funder'
NaN found in row with id 2136, column 'installer'
NaN found in row with id 2136, column 'scheme_name'
NaN found in row with id 33320, column 'scheme_name'
NaN found in row with id 58126, column 'scheme_name'
NaN found in row with id 45604, column 'scheme_name'
NaN found in row with id 67428, column 'scheme_name'
NaN found in row with id 52318, column 'funder'
NaN found in row with id 52318, column 'installer'
NaN found in row with id 52318, column 'scheme_name'
NaN found in row with id 33347, column 'funder'
NaN found in row with id 33347, column 'installer'
NaN found in row with id 33347, column 'public_meeting'
NaN found in row with id 33347, column 'permit'
NaN found in row with id 36684, column 'scheme_name'
NaN found in row with id 41034, column 'scheme_name'
NaN found in row with id 8879, column 'scheme_name'
NaN found in row with id 20203, column 'funder'
NaN found in row with id 20203, column 'installer'
NaN found in row with id 20203, column 'scheme_name'
NaN found in row with id 20203, column 'permit'
NaN found in row with id 8060, column 'scheme_name'
NaN found in row with id 59630, column 'scheme_name'
NaN found in row with id 10068, column 'scheme_name'
NaN found in row with id 34609, column 'funder'
NaN found in row with id 34609, column 'installer'
NaN found in row with id 34609, column 'scheme_name'
NaN found in row with id 26701, column 'scheme_name'
NaN found in row with id 46897, column 'scheme_name'
NaN found in row with id 3181, column 'scheme_name'
NaN found in row with id 43098, column 'funder'
NaN found in row with id 43098, column 'installer'
NaN found in row with id 43098, column 'scheme_name'
NaN found in row with id 37008, column 'scheme_name'
NaN found in row with id 31132, column 'scheme_name'
NaN found in row with id 28740, column 'scheme_name'
NaN found in row with id 30257, column 'funder'
NaN found in row with id 30257, column 'installer'
NaN found in row with id 30257, column 'scheme_name'
NaN found in row with id 30257, column 'permit'
NaN found in row with id 35140, column 'scheme_name'
NaN found in row with id 46814, column 'scheme_name'
NaN found in row with id 7721, column 'scheme_name'
NaN found in row with id 63695, column 'public_meeting'
NaN found in row with id 63695, column 'scheme_management'
NaN found in row with id 63695, column 'scheme_name'
NaN found in row with id 7171, column 'scheme_name'
NaN found in row with id 58838, column 'public_meeting'
NaN found in row with id 58838, column 'scheme_name'
NaN found in row with id 61046, column 'scheme_name'
NaN found in row with id 14746, column 'funder'
NaN found in row with id 14746, column 'installer'
NaN found in row with id 14746, column 'permit'
NaN found in row with id 72374, column 'scheme_name'
NaN found in row with id 33169, column 'scheme_name'
NaN found in row with id 49994, column 'scheme_name'
NaN found in row with id 16944, column 'scheme_name'
NaN found in row with id 70241, column 'funder'
NaN found in row with id 70241, column 'installer'
NaN found in row with id 70241, column 'scheme_name'
NaN found in row with id 35193, column 'scheme_name'
NaN found in row with id 10891, column 'scheme_management'
NaN found in row with id 10891, column 'scheme_name'
NaN found in row with id 1012, column 'scheme_management'
NaN found in row with id 1012, column 'scheme_name'
NaN found in row with id 41162, column 'public_meeting'
NaN found in row with id 41162, column 'scheme_name'
NaN found in row with id 31957, column 'scheme_name'
NaN found in row with id 28110, column 'scheme_name'
NaN found in row with id 62720, column 'scheme_name'
NaN found in row with id 14326, column 'scheme_name'
NaN found in row with id 14326, column 'permit'
NaN found in row with id 36933, column 'scheme_name'
NaN found in row with id 50139, column 'funder'
NaN found in row with id 50139, column 'installer'
NaN found in row with id 50139, column 'permit'
NaN found in row with id 49732, column 'scheme_name'
NaN found in row with id 20200, column 'scheme_name'
NaN found in row with id 42497, column 'public_meeting'
NaN found in row with id 18842, column 'scheme_name'
NaN found in row with id 44434, column 'scheme_name'
NaN found in row with id 36093, column 'scheme_name'
NaN found in row with id 2591, column 'scheme_name'
NaN found in row with id 69669, column 'scheme_name'
NaN found in row with id 51185, column 'scheme_name'
NaN found in row with id 45886, column 'scheme_management'
NaN found in row with id 45886, column 'scheme_name'
NaN found in row with id 64793, column 'scheme_name'
NaN found in row with id 40808, column 'scheme_name'
NaN found in row with id 62565, column 'scheme_name'
NaN found in row with id 10089, column 'scheme_name'
NaN found in row with id 39310, column 'scheme_name'
NaN found in row with id 28945, column 'funder'
NaN found in row with id 28945, column 'installer'
NaN found in row with id 28945, column 'permit'
NaN found in row with id 5074, column 'scheme_name'
NaN found in row with id 54009, column 'funder'
NaN found in row with id 54009, column 'installer'
NaN found in row with id 54009, column 'scheme_name'
NaN found in row with id 17668, column 'scheme_name'
NaN found in row with id 1298, column 'scheme_management'
NaN found in row with id 1298, column 'scheme_name'
NaN found in row with id 2993, column 'scheme_name'
NaN found in row with id 63712, column 'scheme_name'
NaN found in row with id 61979, column 'scheme_name'
NaN found in row with id 39704, column 'scheme_management'
NaN found in row with id 39704, column 'scheme_name'
NaN found in row with id 35649, column 'funder'
NaN found in row with id 35649, column 'installer'
NaN found in row with id 35649, column 'scheme_name'
NaN found in row with id 15840, column 'scheme_management'
NaN found in row with id 15840, column 'scheme_name'
NaN found in row with id 8055, column 'scheme_name'
NaN found in row with id 33963, column 'scheme_management'
NaN found in row with id 33963, column 'scheme_name'
NaN found in row with id 17111, column 'funder'
NaN found in row with id 17111, column 'installer'
NaN found in row with id 17111, column 'scheme_name'
NaN found in row with id 21338, column 'scheme_name'
NaN found in row with id 49326, column 'scheme_name'
NaN found in row with id 15358, column 'scheme_name'
NaN found in row with id 29513, column 'scheme_management'
NaN found in row with id 29513, column 'scheme_name'
NaN found in row with id 51163, column 'scheme_name'
NaN found in row with id 40920, column 'scheme_management'
NaN found in row with id 40920, column 'scheme_name'
NaN found in row with id 21127, column 'subvillage'
NaN found in row with id 8230, column 'scheme_name'
NaN found in row with id 62188, column 'scheme_name'
NaN found in row with id 68887, column 'funder'
NaN found in row with id 68887, column 'installer'
NaN found in row with id 68887, column 'scheme_name'
NaN found in row with id 65238, column 'public_meeting'
NaN found in row with id 65238, column 'scheme_management'
NaN found in row with id 65238, column 'scheme_name'
NaN found in row with id 17897, column 'scheme_name'
NaN found in row with id 26655, column 'scheme_name'
NaN found in row with id 51558, column 'subvillage'
NaN found in row with id 48007, column 'scheme_name'
NaN found in row with id 13969, column 'installer'
NaN found in row with id 25736, column 'scheme_name'
NaN found in row with id 17516, column 'scheme_name'
NaN found in row with id 66980, column 'scheme_name'
NaN found in row with id 45444, column 'scheme_management'
NaN found in row with id 45444, column 'scheme_name'
NaN found in row with id 61883, column 'scheme_management'
NaN found in row with id 61883, column 'scheme_name'
NaN found in row with id 93, column 'scheme_name'
NaN found in row with id 19304, column 'scheme_name'
NaN found in row with id 44092, column 'scheme_name'
NaN found in row with id 51611, column 'scheme_name'
NaN found in row with id 53847, column 'subvillage'
NaN found in row with id 16341, column 'scheme_name'
NaN found in row with id 73470, column 'scheme_name'
NaN found in row with id 11533, column 'scheme_name'
NaN found in row with id 4101, column 'scheme_name'
NaN found in row with id 17041, column 'scheme_name'
NaN found in row with id 39749, column 'public_meeting'
NaN found in row with id 39749, column 'scheme_management'
NaN found in row with id 39749, column 'scheme_name'
NaN found in row with id 56863, column 'scheme_name'
NaN found in row with id 34870, column 'scheme_name'
NaN found in row with id 9736, column 'scheme_management'
NaN found in row with id 9736, column 'scheme_name'
NaN found in row with id 20984, column 'scheme_name'
NaN found in row with id 20132, column 'scheme_management'
NaN found in row with id 20132, column 'scheme_name'
NaN found in row with id 5963, column 'scheme_name'
NaN found in row with id 26943, column 'scheme_name'
NaN found in row with id 43742, column 'scheme_name'
NaN found in row with id 5784, column 'scheme_name'
NaN found in row with id 5121, column 'scheme_name'
NaN found in row with id 57478, column 'scheme_name'
NaN found in row with id 15832, column 'public_meeting'
NaN found in row with id 67097, column 'scheme_name'
NaN found in row with id 39559, column 'scheme_name'
NaN found in row with id 54412, column 'funder'
NaN found in row with id 54412, column 'installer'
NaN found in row with id 54412, column 'scheme_name'
NaN found in row with id 25344, column 'scheme_name'
NaN found in row with id 32844, column 'funder'
NaN found in row with id 32844, column 'installer'
NaN found in row with id 32844, column 'permit'
NaN found in row with id 59874, column 'scheme_name'
NaN found in row with id 50233, column 'scheme_name'
NaN found in row with id 29639, column 'scheme_name'
NaN found in row with id 43808, column 'scheme_name'
NaN found in row with id 16872, column 'funder'
NaN found in row with id 16872, column 'installer'
NaN found in row with id 16872, column 'permit'
NaN found in row with id 58599, column 'scheme_name'
NaN found in row with id 29383, column 'scheme_name'
NaN found in row with id 36809, column 'scheme_name'
NaN found in row with id 29753, column 'scheme_name'
NaN found in row with id 72112, column 'public_meeting'
NaN found in row with id 72112, column 'scheme_name'
NaN found in row with id 34926, column 'scheme_name'
NaN found in row with id 68126, column 'scheme_management'
NaN found in row with id 68126, column 'scheme_name'
NaN found in row with id 48102, column 'public_meeting'
NaN found in row with id 24794, column 'scheme_name'
NaN found in row with id 29771, column 'scheme_name'
NaN found in row with id 4923, column 'funder'
NaN found in row with id 4923, column 'installer'
NaN found in row with id 4923, column 'permit'
NaN found in row with id 27079, column 'scheme_name'
NaN found in row with id 12478, column 'scheme_name'
NaN found in row with id 54733, column 'scheme_name'
NaN found in row with id 45654, column 'scheme_management'
NaN found in row with id 45654, column 'scheme_name'
NaN found in row with id 1439, column 'scheme_name'
NaN found in row with id 16313, column 'scheme_name'
NaN found in row with id 1220, column 'scheme_name'
NaN found in row with id 57970, column 'scheme_name'
NaN found in row with id 40519, column 'scheme_name'
NaN found in row with id 45386, column 'scheme_name'
NaN found in row with id 1030, column 'scheme_name'
NaN found in row with id 52677, column 'scheme_name'
NaN found in row with id 1738, column 'scheme_management'
NaN found in row with id 1738, column 'scheme_name'
NaN found in row with id 19548, column 'scheme_name'
NaN found in row with id 27523, column 'scheme_name'
NaN found in row with id 815, column 'public_meeting'
NaN found in row with id 11184, column 'funder'
NaN found in row with id 11184, column 'installer'
NaN found in row with id 11184, column 'scheme_name'
NaN found in row with id 11184, column 'permit'
NaN found in row with id 49071, column 'permit'
NaN found in row with id 22000, column 'scheme_name'
NaN found in row with id 6205, column 'scheme_name'
NaN found in row with id 16537, column 'scheme_name'
NaN found in row with id 9096, column 'scheme_name'
NaN found in row with id 33104, column 'scheme_name'

What are the columns containing NaNs?

In [5]:
cols_with_nan = df.columns[df.isna().any()].tolist()
print(cols_with_nan)

['funder', 'installer', 'wpt_name', 'subvillage', 'public_meeting', 'scheme_management', 'scheme_name', 'permit']

In [6]:
for col in cols_with_nan:
    if df[col].dtype == 'object':
        print(f"\nColumn: {col}")
        print("Value Counts:")
        print(df[col].value_counts(dropna=True))
        print(f"Number of NaNs: {df[col].isna().sum()}")

Column: funder
Value Counts:
funder
Government Of Tanzania    8842
Danida                    3114
Hesawa                    1914
World Bank                1345
Kkkt                      1287
                          ...
Sent Tho                     1
Rilayo Water Project         1
Dwe/anglican Church          1
Cida                         1
Wanginyi Water               1
Name: count, Length: 1857, dtype: int64
Number of NaNs: 3624

Column: installer
Value Counts:
installer
DWE                 16255
Government           1670
RWE                  1181
Commu                1060
DANIDA               1050
                    ...
MSIGWA                  1
harison                 1
MW                      1
Water user Group        1
CONCE                   1
Name: count, Length: 2113, dtype: int64
Number of NaNs: 3636

Column: wpt_name
Value Counts:
wpt_name
none                          3492
Shuleni                       1734
Zahanati                       814
Msikitini                      533
Kanisani                       322
                              ...
Kwa Ochora                       1
Mzuu                             1
Kwa Simon Methew                 1
Kwa Lugano Kahenge               1
Kilimanjaro Primary School       1
Name: count, Length: 36719, dtype: int64
Number of NaNs: 2

Column: subvillage
Value Counts:
subvillage
Majengo         494
Shuleni         492
Madukani        435
Kati            366
Mtakuja         257
               ...
Tuzimu            1
Sadan A           1
Mwambogwa         1
Kavuga            1
Ngondombwito      1
Name: count, Length: 18567, dtype: int64
Number of NaNs: 371

Column: public_meeting
Value Counts:
public_meeting
True     49737
False     4875
Name: count, dtype: int64
Number of NaNs: 2976

Column: scheme_management
Value Counts:
scheme_management
VWC                 36143
WUG                  4249
Water authority      3151
WUA                  2882
Water Board          2747
Parastatal           1607
Private operator     1063
Company              1061
Other                 765
SWC                    97
Trust                  72
Name: count, dtype: int64
Number of NaNs: 3751

Column: scheme_name
Value Counts:
scheme_name
K                     682
Borehole              418
Chalinze wate         405
M                     400
DANIDA                379
                     ...
Sukuro pipe scheme      1
Kibena                  1
BL RC                   1
Rodosi                  1
Mwese water supply      1
Name: count, Length: 2657, dtype: int64
Number of NaNs: 27336

Column: permit
Value Counts:
permit
True     38100
False    16432
Name: count, dtype: int64
Number of NaNs: 3056

Try dropping all rows with NaNs. How much of dataset is lost?

In [7]:
clean_df = df.dropna()
clean_df

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
5,9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587,Tajiri,0,...,per bucket,salty,salty,enough,enough,other,other,unknown,communal standpipe multiple,communal standpipe
13,50495,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783,Kwa John Izack Mmari,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
16,48451,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185,Kwa John Mtenzi,0,...,monthly,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59381,67885,0.0,2011-03-16,Mkinga Distric Coun,0,DWE,38.835001,-4.880204,Mijohoroni,0,...,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
59382,47002,6.0,2013-08-03,Ces(gmbh),1383,DWE,37.454759,-3.323599,Kwa Luka Msaki,0,...,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59391,44885,0.0,2013-08-03,Government Of Tanzania,540,Government,38.044070,-4.272218,Kwa,0,...,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59395,60739,10.0,2013-05-03,Germany Republi,1210,CES,37.169807,-3.253847,Area Three Namba 27,0,...,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59396,27263,4700.0,2011-05-07,Cefa-njombe,1212,Cefa,35.249991,-9.070629,Kwa Yahona Kuvala,0,...,annually,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe

Dropping from 59400 rows of data to 26839 is bad. Fill in the NaNs with..?

In [ ]:
for col in num_cols:
    sns.boxplot(x=df['target'], y=df[col])
    plt.title(col)
    plt.show()

In [38]:
col = 'region'

if df[col].dtype == 'object':
    print(f"\nColumn: {col}")
    print("Value Counts:")
    print(df[col].value_counts(dropna=True))
    print(f"Number of NaNs: {df[col].isna().sum()}")

Column: region
Value Counts:
region
Iringa           5294
Mbeya            4639
Kilimanjaro      4379
Morogoro         4006
Shinyanga        3977
Arusha           3350
Kagera           3316
Kigoma           2816
Ruvuma           2640
Pwani            2635
Tanga            2547
Mwanza           2295
Dodoma           2201
Singida          2093
Mara             1969
Tabora           1959
Rukwa            1808
Mtwara           1730
Manyara          1583
Lindi            1546
Dar es Salaam     805
Name: count, dtype: int64
Number of NaNs: 0

In [40]:
col_2 = 'region_code'

print(f"\nColumn: {col_2}")
print("Value Counts:")
print(df[col_2].value_counts(dropna=True))
print(f"Number of NaNs: {df[col_2].isna().sum()}")

Column: region_code
Value Counts:
region_code
11    5297
12    4639
3     4379
5     4040
17    3954
18    3324
2     3024
16    2816
10    2640
4     2513
19    2295
1     2201
13    2093
14    1979
20    1969
15    1808
6     1609
21    1583
80    1238
60    1025
90     917
7      805
99     423
9      390
24     326
8      300
40       1
Name: count, dtype: int64
Number of NaNs: 0

### print(df.columns.tolist())

In [16]:
geo_cols = ['gps_height', 'longitude', 'latitude', 'basin', 'region', 'region_code',
            'district_code', 'lga', 'ward', 'subvillage']

geo_df = df[geo_cols].copy()

In [17]:
geo_df

,gps_height,longitude,latitude,basin,region,region_code,district_code,lga,ward,subvillage
0,1390,34.938093,-9.856322,Lake Nyasa,Iringa,11,5,Ludewa,Mundindi,Mnyusi B
1,1399,34.698766,-2.147466,Lake Victoria,Mara,20,2,Serengeti,Natta,Nyamara
2,686,37.460664,-3.821329,Pangani,Manyara,21,4,Simanjiro,Ngorika,Majengo
3,263,38.486161,-11.155298,Ruvuma / Southern Coast,Mtwara,90,63,Nanyumbu,Nanyumbu,Mahakamani
4,0,31.130847,-1.825359,Lake Victoria,Kagera,18,1,Karagwe,Nyakasimbi,Kyanyamisa
...,...,...,...,...,...,...,...,...,...,...
59395,1210,37.169807,-3.253847,Pangani,Kilimanjaro,3,5,Hai,Masama Magharibi,Kiduruni
59396,1212,35.249991,-9.070629,Rufiji,Iringa,11,4,Njombe,Ikondo,Igumbilo
59397,0,34.017087,-8.750434,Rufiji,Mbeya,12,7,Mbarali,Chimala,Madungulu
59398,0,35.861315,-6.378573,Rufiji,Dodoma,1,4,Chamwino,Mvumi Makulu,Mwinyi
59399,191,38.104048,-6.747464,Wami / Ruvu,Morogoro,5,2,Morogoro Rural,Ngerengere,Kikatanyemba

Checking the columns source, source_type and source_class

source_type is redundant, repeats information from source class.

In [48]:
df.groupby(['source', 'source_type'])['source_class'].value_counts().unstack().fillna(0)

source_class                               groundwater  surface  unknown
source               source_type
dam                  dam                           0.0    649.0      0.0
hand dtw             borehole                    873.0      0.0      0.0
lake                 river/lake                    0.0    639.0      0.0
machine dbh          borehole                  10826.0      0.0      0.0
other                other                         0.0      0.0    202.0
rainwater harvesting rainwater harvesting          0.0   2218.0      0.0
river                river/lake                    0.0   9612.0      0.0
shallow well         shallow well              15499.0      0.0      0.0
spring               spring                    17006.0      0.0      0.0
unknown              other                         0.0      0.0     64.0

same as previous cell. waterpoint_type offers more information about "communal standpipe" and "communal standpipe multiple". Otherwise its same information in two coulmns, so drop the column waterpoint_type_group.

In [49]:
df.groupby(['waterpoint_type'])['waterpoint_type_group'].value_counts().unstack().fillna(0)

waterpoint_type_group,cattle trough,communal standpipe,dam,hand pump,improved spring,other
waterpoint_type,,,,,,
cattle trough,116.0,0.0,0.0,0.0,0.0,0.0
communal standpipe,0.0,28375.0,0.0,0.0,0.0,0.0
communal standpipe multiple,0.0,5959.0,0.0,0.0,0.0,0.0
dam,0.0,0.0,7.0,0.0,0.0,0.0
hand pump,0.0,0.0,0.0,16181.0,0.0,0.0
improved spring,0.0,0.0,0.0,0.0,783.0,0.0
other,0.0,0.0,0.0,0.0,0.0,6167.0

Drop quality_group

In [52]:
df.groupby(['water_quality'])['quality_group'].value_counts().unstack().fillna(0)

quality_group       colored  fluoride     good  milky   salty  unknown
water_quality
coloured              479.0       0.0      0.0    0.0     0.0      0.0
fluoride                0.0     199.0      0.0    0.0     0.0      0.0
fluoride abandoned      0.0      15.0      0.0    0.0     0.0      0.0
milky                   0.0       0.0      0.0  803.0     0.0      0.0
salty                   0.0       0.0      0.0    0.0  4772.0      0.0
salty abandoned         0.0       0.0      0.0    0.0   228.0      0.0
soft                    0.0       0.0  49431.0    0.0     0.0      0.0
unknown                 0.0       0.0      0.0    0.0     0.0   1661.0

drop quantity_group

In [53]:
df.groupby(['quantity'])['quantity_group'].value_counts().unstack().fillna(0)

quantity_group     dry   enough  insufficient  seasonal  unknown
quantity
dry             5990.0      0.0           0.0       0.0      0.0
enough             0.0  32260.0           0.0       0.0      0.0
insufficient       0.0      0.0       14564.0       0.0      0.0
seasonal           0.0      0.0           0.0    4001.0      0.0
unknown            0.0      0.0           0.0       0.0    773.0

In the case of extraction_type, perhaps extraction_type_class offers enough information about the extraction type?

In [55]:
df.groupby(['extraction_type', 'extraction_type_group'])['extraction_type_class'].value_counts().unstack().fillna(0)

,extraction_type_class,gravity,handpump,motorpump,other,rope pump,submersible,wind-powered
extraction_type,extraction_type_group,,,,,,,
afridev,afridev,0.0,1659.0,0.0,0.0,0.0,0.0,0.0
cemo,other motorpump,0.0,0.0,90.0,0.0,0.0,0.0,0.0
climax,other motorpump,0.0,0.0,32.0,0.0,0.0,0.0,0.0
gravity,gravity,26696.0,0.0,0.0,0.0,0.0,0.0,0.0
india mark ii,india mark ii,0.0,2284.0,0.0,0.0,0.0,0.0,0.0
india mark iii,india mark iii,0.0,91.0,0.0,0.0,0.0,0.0,0.0
ksb,submersible,0.0,0.0,0.0,0.0,0.0,1358.0,0.0
mono,mono,0.0,0.0,2817.0,0.0,0.0,0.0,0.0
nira/tanira,nira/tanira,0.0,7361.0,0.0,0.0,0.0,0.0,0.0
other,other,0.0,0.0,0.0,6160.0,0.0,0.0,0.0
other - mkulima/shinyanga,other handpump,0.0,2.0,0.0,0.0,0.0,0.0,0.0
other - play pump,other handpump,0.0,85.0,0.0,0.0,0.0,0.0,0.0
other - rope pump,rope pump,0.0,0.0,0.0,0.0,451.0,0.0,0.0
other - swn 81,other handpump,0.0,229.0,0.0,0.0,0.0,0.0,0.0
submersible,submersible,0.0,0.0,0.0,0.0,0.0,4688.0,0.0
swn 80,swn 80,0.0,3448.0,0.0,0.0,0.0,0.0,0.0
walimi,other handpump,0.0,20.0,0.0,0.0,0.0,0.0,0.0
windmill,wind-powered,0.0,0.0,0.0,0.0,0.0,0.0,117.0

In [57]:
df.groupby(['region'])['region_code'].value_counts().unstack().fillna(0)
grouped = df.groupby(['region'])['region_code'].nunique().reset_index()
grouped = grouped.rename(columns={'region_code': 'n_unique_region_code'})
print(grouped.sort_values('n_unique_region_code', ascending=False))

           region  n_unique_region_code
7           Lindi                     3
14          Pwani                     3
17      Shinyanga                     3
12         Mtwara                     3
0          Arusha                     2
20          Tanga                     2
3          Iringa                     1
2          Dodoma                     1
1   Dar es Salaam                     1
4          Kagera                     1
8         Manyara                     1
6     Kilimanjaro                     1
5          Kigoma                     1
11       Morogoro                     1
10          Mbeya                     1
9            Mara                     1
13         Mwanza                     1
16         Ruvuma                     1
15          Rukwa                     1
18        Singida                     1
19         Tabora                     1